playertracker3/playertracker3/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^tracker/', include('tracker.urls', namespace="tracker")),
    url(r'^admin/', include(admin.site.urls))
]

playertracker3/tracker/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<player_id>[0-9]+)/$', views.player, name='player')
]

playertracker3/tracker/models.py
from django.db import models

# Create your models here.

class Player(models.Model):
	player_name = models.CharField(max_length=200, default = 'default_value')
	touchdowns = models.IntegerField(default=0)
	def __unicode__(self):
		return self.player_name

playertracker3/tracker/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.http import Http404
from .models import Player

# Create your views here.

def index(request):
	player_list = Player.objects.all()
	
	context =  {	'player_list': player_list}
	
	return render(request, 'tracker/index.html', context)
	
def player(request, player_id):
	player = get_object_or_404(Player, pk=player_id)
	return render(request, 'tracker/player.html', {'player': player})

playertracker3/tracker/templates/tracker/index.html
{% if player_list %}
	<ul>
	{% for player in player_list %}
		<li><a href="{% url 'tracker:player' player.id %}">{{ player.player_name }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No Players are available.</p>
{% endif %}

playertracker3/tracker/templates/tracker/player.html
<h1>{{ player.player_name }}</h1>
<h2>{{ player.touchdowns }} </h2>

{% if error_message %} <p><strong>{{ error_message </strong></p>{% endif %}

<form action = "{% url 'tracker:player' player.id %}" method="post">
   {% csrf_token %}
    {% for choice in player.player_name.all %}
        <input type = "text" name="select_player" id="select_player"{{ forloop.counter }}" value="{{ choice.id }}" />